services:
  - type: web
    name: sinhala-ner-labelstudio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: label-studio start --host 0.0.0.0 --port $PORT
    envVars:
      - key: LABEL_STUDIO_USERNAME
        value: admin@yourgroup.com
      - key: LABEL_STUDIO_PASSWORD
        value: yourpassword123
      - key: LABEL_STUDIO_HOST
        value: https://labelstudio-eyax.onrender.com
      - key: CSRF_COOKIE_SECURE
        value: "0"
      - key: CSRF_COOKIE_HTTPONLY
        value: "0"
      - key: CSRF_TRUSTED_ORIGINS
        value: https://labelstudio-eyax.onrender.com
      - key: ALLOWED_HOSTS
        value: labelstudio-eyax.onrender.com