services:
  - type: web
    name: sinhala-ner-labelstudio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: label-studio start --host 0.0.0.0 --port $PORT --log-level DEBUG
    envVars:
      - key: LABEL_STUDIO_USERNAME
        value: admin@yourgroup.com
      - key: LABEL_STUDIO_PASSWORD
        value: yourpassword123
      - key: LABEL_STUDIO_HOST
        value: https://labelstudio-eyax.onrender.com
      - key: DEBUG
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "False"
      - key: CSRF_COOKIE_HTTPONLY
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: label_studio.settings.label_studio
      - key: LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK
        value: "false"